version = 1

test_patterns = ["tests/**"]

[[analyzers]]
name = "shell"
enabled = true

[[analyzers]]
name = "docker"
enabled = true

[[analyzers]]
name = "terraform"
enabled = true

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"
  max_line_length = 90

[[transformers]]
name = "black"
enabled = true
